# Generated by Django 5.0.3 on 2024-03-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Board',
                'verbose_name_plural': "Post Board's",
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='post title')),
                ('content', models.TextField(max_length=450, verbose_name='content')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('viewers', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='viewers count')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('board', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to='post.board', verbose_name='post board')),
            ],
            options={
                'verbose_name': 'Blog Posts',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
    ]
