# Generated by Django 5.0.3 on 2024-04-05 20:08

import smuull.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_board_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=smuull.post.models.post_cover_upload_dir, verbose_name='post image'),
        ),
    ]
