# Generated by Django 5.0.3 on 2024-03-30 11:40

import smuull.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=smuull.accounts.models.avatar_upload_dir, verbose_name='profile pic.'),
        ),
    ]
