# Generated by Django 5.0.3 on 2024-03-30 12:30

import smuull.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_created_at_profile_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=smuull.accounts.models.avatar_upload_dir, verbose_name='profile pic.'),
        ),
    ]
