# Generated by Django 5.0.3 on 2024-03-30 12:31

import smuull.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=smuull.accounts.models.avatar_upload_dir, verbose_name='profile pic.'),
        ),
    ]
